name: Deploy to DotRoll

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      REMOTE_PATH: ${{ secrets.REMOTE_PATH }}

    steps:
      - name: Marker
        run: echo "WORKFLOW VERSION: 2025-10-01-01"

      - uses: actions/checkout@v4

      - name: Setup SSH (decode key, add host)
        shell: bash
        run: |
          set -euo pipefail
          PORT="${SSH_PORT:-22}"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "$PORT" "$SSH_HOST" >> ~/.ssh/known_hosts
          ssh -p "$PORT" -o BatchMode=yes "$SSH_USER@$SSH_HOST" \
            "mkdir -p '$REMOTE_PATH' && echo 'SSH OK'"

      - name: Upload (streaming tar over SSH)
        shell: bash
        run: |
          set -euo pipefail
          PORT="${SSH_PORT:-22}"
          tar -cz --warning=no-file-changed \
            --exclude='.git' --exclude='.github' --exclude='.env' . \
          | ssh -p "$PORT" "$SSH_USER@$SSH_HOST" \
              "cd '$REMOTE_PATH' && tar -xzf - && ls -la"
